# -*- coding: utf-8 -*-
"""
基礎年金/snaps.h・mfile_open.h・option.h の定数
================================================
原本の `#define` をそのまま並べたもの。名前は1文字も変えていない。

①⑤⑥と違って**年度の添字がシステム内で2種類ある**
-----------------------------------------------------
    人数・給付費の配列   `nendo - SHONENDO`        （SHONENDO = 2020）
    経済前提の配列       `nendo - ECON_SHONENDO`   （ECON_SHONENDO = 2001）

`Cut_ritu` だけは `nenrei - UNDER_63`、`Kyufu` などは `nenrei - NENREI_SUM`
と年齢の原点も2種類ある。`NENREI_SUM`（62）は「年齢計」の置き場で、
実データが入るのは `UNDER_63`（63）以上。

`SEIDO_KUBUN` などの「区分の数」と `KOKUNEN` などの「区分の値」が
同じヘッダに混ざっているので、配列の寸法は `glva.py` の表を見ること。
"""

__all__ = [
    "EPSILON", "KAKO", "KAKO_J",
    "SHONENDO", "ECON_SHONENDO", "SOTOWAKU_SHONENDO", "KAKAKU_NENDO",
    "SUIKEISHONENDO", "SAISHUNENDO", "SUIKEISAISHUNENDO", "R_S_C_NENDO",
    "TUMATUMI_NENDO", "TUMATUMI_KIKAN", "SOTOWAKU_SAISHUNENDO",
    "SUM", "SEIDO_KUBUN", "KOKUNEN", "KOUNEN", "KOKKYO", "CHIKYO",
    "SHIGAKU", "BUNPAI",
    "SHIKYU_KEITAI", "KIHON", "KAKYU",
    "SHINKYU", "NEW", "OLD",
    "SEIBETU", "OTOKO", "ONNA",
    "NOUFU_JOTAI_SHIN", "NOUFU", "MENJO_ZENHAN", "MENJO_KOUHAN",
    "NOUFU_JOTAI_KYU", "MENJO", "KAKYU_NOUFU", "KAKYU_MENJO",
    "KASANOUFU", "KASAMENJO", "ROFUKU_SHITASASAE", "GONEN",
    "KYUFU_HOUHOU", "IPPAN", "HATACHIMAE",
    "KYUFU_TAISHOU", "KYOSHUTU", "TOKUBETU",
    "KYUFU_KUBUN", "ROREI", "SHOGAI", "IZOKU",
    "TOKUBETU_SHURUI", "TOKUBETU_MENJO", "TOKUBETU_KASAAGE",
    "TOKUBETU_KASAMENJO", "TOKUBETU_SHITASASAE", "TOKUBETU_GONEN",
    "TOKUBETU_20MAE",
    "FUKA", "OLD_NOUFU", "OLD_MENJO", "OLD_ROREI", "OLD_TURO",
    "MAX_JUKYU", "MAX_HIHO_NENREI", "MIN_HIHO_NENREI", "HIHO_NENREI_SUM",
    "MAX_KYOSHUTU_NENREI", "NENREI_SUM", "UNDER_63", "UNDER_64", "UNDER_67",
    "DATA_MAX", "DATA_MAX_C", "BUFFER_MAX",
    "INFILE_NUM", "OUTFILE_NUM",
    "DOKUZI", "KEIZAI", "KAITEI", "TANNEN_CUT", "HOKEN", "YUUSHI",
    "zisseki_hosei", "SOTOWAKU_START", "KOKUNEN_1GOU", "KOUNEN_2GOU",
    "KOKKYOU_2GOU", "CHIKYOU_2GOU", "SHIGAKU_2GOU", "KOUNEN_3GOU",
    "KOKKYOU_3GOU", "CHIKYOU_3GOU", "SHIGAKU_3GOU", "CUT", "CUT_K",
    "SETTEI", "KYOSHUTUKIN", "TUMATUMI_OUT", "KEKKA_b", "KEKKA_a",
    "CUTA", "OUTPUT", "PROVIDE",
    "OP_MAX_KYOSHUTU_NENREI",
    "NY", "NJ", "NE", "NC",
]

# ---- snaps.h ----
EPSILON = 1.0e-14

KAKO = "AK"
KAKO_J = "AJ"

SHONENDO = 2020
ECON_SHONENDO = 2001
SOTOWAKU_SHONENDO = 2021
KAKAKU_NENDO = 2004
SUIKEISHONENDO = 2020
SAISHUNENDO = 2125
SUIKEISAISHUNENDO = 2125
R_S_C_NENDO = 2120
TUMATUMI_NENDO = 2015
TUMATUMI_KIKAN = 10
SOTOWAKU_SAISHUNENDO = 2125

SUM = 0
SEIDO_KUBUN = 6
KOKUNEN = 1
KOUNEN = 2
KOKKYO = 3
CHIKYO = 4
SHIGAKU = 5
BUNPAI = 6

SHIKYU_KEITAI = 3
KIHON = 1
KAKYU = 2

SHINKYU = 3
NEW = 1
OLD = 2

SEIBETU = 3
OTOKO = 1
ONNA = 2

NOUFU_JOTAI_SHIN = 4
NOUFU = 1
MENJO_ZENHAN = 2
MENJO_KOUHAN = 3
NOUFU_JOTAI_KYU = 9
MENJO = 2
KAKYU_NOUFU = 3
KAKYU_MENJO = 4
KASANOUFU = 5
KASAMENJO = 6
ROFUKU_SHITASASAE = 7
GONEN = 8

KYUFU_HOUHOU = 3
IPPAN = 1
HATACHIMAE = 2

KYUFU_TAISHOU = 3
KYOSHUTU = 1
TOKUBETU = 2

KYUFU_KUBUN = 4
ROREI = 1
SHOGAI = 2
IZOKU = 3

TOKUBETU_SHURUI = 7
TOKUBETU_MENJO = 1
TOKUBETU_KASAAGE = 2
TOKUBETU_KASAMENJO = 3
TOKUBETU_SHITASASAE = 4
TOKUBETU_GONEN = 5
TOKUBETU_20MAE = 6

# `FUKA`（付加。一時金・保険料の区分 2）。mkiso.h の配列 `Fuka` とは
# 大文字小文字だけの違いで別物。移植版でも定数 `FUKA` と `G.Fuka` に分ける。
FUKA = 2

OLD_NOUFU = 2
OLD_MENJO = 3
OLD_ROREI = 2
OLD_TURO = 3

MAX_JUKYU = 115
MAX_HIHO_NENREI = 70
MIN_HIHO_NENREI = 20
HIHO_NENREI_SUM = 19
MAX_KYOSHUTU_NENREI = 60
NENREI_SUM = 62
UNDER_63 = 63
UNDER_64 = 64
UNDER_67 = 67

DATA_MAX = 1000
DATA_MAX_C = 1000
BUFFER_MAX = 1000

# ---- mfile_open.h ----
INFILE_NUM = 23
OUTFILE_NUM = 8

DOKUZI = 0
KEIZAI = 6
KAITEI = 7
TANNEN_CUT = 8
HOKEN = 9
YUUSHI = 10
zisseki_hosei = 11
SOTOWAKU_START = 12
KOKUNEN_1GOU = 12
KOUNEN_2GOU = 13
KOKKYOU_2GOU = 14
CHIKYOU_2GOU = 15
SHIGAKU_2GOU = 16
KOUNEN_3GOU = 17
KOKKYOU_3GOU = 18
CHIKYOU_3GOU = 19
SHIGAKU_3GOU = 20
CUT = 21
CUT_K = 22

SETTEI = 0
KYOSHUTUKIN = 1
TUMATUMI_OUT = 2
KEKKA_b = 3
KEKKA_a = 4
CUTA = 5
OUTPUT = 6
PROVIDE = 7

# ---- option.h ----
OP_MAX_KYOSHUTU_NENREI = 65

# ---- 配列の寸法（原本の式をそのまま計算したもの） ----
NY = SAISHUNENDO - SHONENDO + 1            # 106  年度（人数・給付費）
NJ = MAX_JUKYU - NENREI_SUM + 1            #  54  年齢（62〜115）
NE = SAISHUNENDO - ECON_SHONENDO + 1       # 125  年度（経済前提）
NC = MAX_JUKYU - UNDER_67 + 1              #  49  年齢（67〜115）
